<template>
	<!-- eslint-disable vue/no-v-html -->
	<div class="wbmi-media-search-quick-view">
		<header class="wbmi-media-search-quick-view__header">
			<img :src="thumbnail" class="wbmi-media-search-quick-view__thumbnail">

			<button class="wbmi-media-search-quick-view__close-button" @click="close">
				X
			</button>
		</header>

		<!-- File details: most of this information comes from the Commons
		Metadata API; the data available for a given file can vary widely and
		may include complex HTML generated by templates. -->
		<div class="wbmi-media-search-quick-view__body">
			<h3><a :href="canonicalurl">{{ title }}</a></h3>

			<p v-if="description"
				class="wbmi-media-search-quick-view__description"
				v-html="description">
			</p>

			<p v-if="artist">
				<mw-icon :icon="'userAvatar'"></mw-icon>
				<span v-html="artist"></span>
			</p>

			<!-- Attempt to show license text, an appropriate icon, and an
			optional link to external license URL -->
			<p v-if="licenseText">
				<mw-icon v-if="licenseIcon" :icon="licenseIcon"></mw-icon>
				<a v-if="licenseUrl"
					:href="licenseUrl"
					target="_blank">
					<span v-html="licenseText"></span>
				</a>
				<span v-else v-html="licenseText"></span>
			</p>

			<!-- Sometimes this is free text, sometimes it is formatted. Can
			we make things semi-consistent? -->
			<p v-if="creationDate">
				<mw-icon :icon="'clock'"></mw-icon>
				<span v-html="creationDate"></span>
			</p>

			<p v-if="resolution">
				<mw-icon :icon="'camera'"></mw-icon>
				<span>{{ resolution }}</span>
			</p>

			<p v-if="mimeType">
				<mw-icon :icon="'pageSettings'"></mw-icon>
				<span>{{ mimeType }}</span>
			</p>

			<p>
				<mw-button
					:icon="'logoWikimediaCommons'"
					:primary="true"
					:progressive="true"
					@click="goToFilePage( canonicalurl )">
					More Details
				</mw-button>
			</p>
		</div>
	</div>
</template>

<script>
var Icon = require( './base/Icon.vue' ),
	Button = require( './base/Button.vue' );
/**
 * @file QuickView.vue
 *
 * Component to display expanded details about a given search result
 */
// @vue/component
module.exports = {
	name: 'QuickView',

	components: {
		'mw-icon': Icon,
		'mw-button': Button
	},

	props: {
		title: {
			type: String,
			required: true
		},

		canonicalurl: {
			type: String,
			required: true
		},

		pageid: {
			type: Number,
			required: true
		},

		imageinfo: {
			type: Array,
			required: false,
			default: function () {
				return [ {} ];
			}
		}
	},

	computed: {
		/**
		 * @return {string|undefined}
		 */
		thumbnail: function () {
			return this.imageinfo[ 0 ].thumburl;
		},

		/**
		 * @return {Object|undefined}
		 */
		metadata: function () {
			return this.imageinfo[ 0 ].extmetadata;
		},

		/**
		 * @return {string|null} String that may contain HTML
		 */
		description: function () {
			if ( this.metadata && this.metadata.ImageDescription ) {
				return this.metadata.ImageDescription.value;
			} else {
				return null;
			}
		},

		/**
		 * @return {string|null} String that may contain HTML (often a link to a User page)
		 */
		artist: function () {
			if ( this.metadata && this.metadata.Artist ) {
				return this.metadata.Artist.value;
			} else {
				return null;
			}
		},

		/**
		 * @return {string|null}
		 */
		licenseText: function () {
			if ( this.metadata ) {
				return this.metadata.UsageTerms.value;
			} else {
				return null;
			}
		},

		licenseIcon: function () {
			if ( this.metadata && this.metadata.License ) {
				return this.getLicenseIcon( this.metadata.License.value );
			} else {
				return null;
			}
		},

		licenseUrl: function () {
			if ( this.metadata && this.metadata.LicenseUrl ) {
				return this.metadata.LicenseUrl.value;
			} else {
				return null;
			}
		},

		/**
		 * @return {string|null} String that may contain HTML
		 */
		creationDate: function () {
			if ( this.metadata && this.metadata.DateTimeOriginal ) {
				return this.metadata.DateTimeOriginal.value;
			} else {
				return null;
			}
		},

		/**
		 * @return {string|null}
		 */
		resolution: function () {
			var width = this.imageinfo[ 0 ].width,
				height = this.imageinfo[ 0 ].height;

			if ( this.imageinfo && width && height ) {
				return width + ' × ' + height;
			} else {
				return null;
			}
		},

		mimeType: function () {
			return this.imageinfo[ 0 ].mime;
		}
	},

	methods: {
		close: function () {
			this.$emit( 'close' );
		},

		/**
		 * Use this method if a non-HTML metadata value is required.
		 *
		 * @param {string} raw HTML string
		 * @return {string}
		 */
		stripHTML: function ( raw ) {
			return $( '<p>' ).append( raw ).text();
		},

		getLicenseIcon: function ( valueString ) {
			if ( /^cc/i.test( valueString ) ) {
				return 'logoCC';
			} else if ( /^pd/i.test( valueString ) ) {
				return 'unLock';
			} else {
				return null;
			}
		},

		goToFilePage: function ( url ) {
			window.location = url;
		}
	}
};
</script>

<style lang="less">
@import 'mediawiki.mixins';
@import '../../../lib/wikimedia-ui-base.less';

.wbmi-media-search-quick-view {
	border: @border-base;
	border-radius: 4px;
	box-sizing: @box-shadow-card;
	position: sticky;
	margin-top: 8px;
	top: 8px;

	&__thumbnail {
		background-color: @wmui-color-base70;
		object-fit: contain;
		height: auto;
		max-height: 300px;
		width: 100%;
	}

	&__close-button {
		position: absolute;
		top: 8px;
		left: 8px;
	}

	&__body {
		padding: 16px;

		.mw-icon {
			opacity: 0.33;
			margin-right: 4px;
		}
	}

	&__description {
		max-height: 600px;
		overflow: scroll;
		-webkit-overflow-scrolling: touch;

		// We really have no idea what we will find here; hopefully we can force it
		// to fit...
		> * {
			max-width: 100%;
		}
	}
}
</style>
